In [9]:
x,y = 2,3
a,b,c,d = 1,2,3,4

In [12]:
print(x&y)
print(x|y)
print(~x)
print(x^y)
print(x>>y)
print(x<<y)

2 0
3 7
-3
1
0
16


## **Numpy**

## *Numpy*

## Numpy

In [2]:
! pip install numpy

     ---------------------------------------- 14.9/14.9 MB 7.4 MB/s eta 0:00:00


You should consider upgrading via the 'C:\Users\anand\Downloads\PYF2\0 Git repos (X don't delete)\repos\Scripts\python.exe -m pip install --upgrade pip' command.


In [3]:
import numpy as np

In [4]:
a1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [16]:
print(np.arange(0,10), type(np.arange(0,10)))
print(np.arange(10))
print(np.arange(0,20,2))

print(np.zeros(10))
print(np.zeros((3,4)))
print(np.ones(10))
print(np.ones((4,3)))
print(np.eye(3))

[0 1 2 3 4 5 6 7 8 9] <class 'numpy.ndarray'>
[0 1 2 3 4 5 6 7 8 9]
[ 0  2  4  6  8 10 12 14 16 18]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [30]:
x = np.arange(9)
print(x.reshape(3,3))

print(np.linspace(0,10,5))
print(np.linspace(0,10,11))
print(np.linspace(0,10,21))

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[ 0.   2.5  5.   7.5 10. ]
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
[ 0.   0.5  1.   1.5  2.   2.5  3.   3.5  4.   4.5  5.   5.5  6.   6.5
  7.   7.5  8.   8.5  9.   9.5 10. ]


In [31]:
x = np.arange(9)
print(x.reshape(3,3))
print(x)

x.resize(3,3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[0 1 2 3 4 5 6 7 8]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [38]:
print(' uniform distribution')
print(np.random.rand(2,3))
print(np.random.rand(2,3))

print('\n normal distribution')
print(np.random.randn(2,3))
print(np.random.randn(2,3))

print('\n random integer')
print(np.random.randint(2,30))
print(np.random.randint(2,30,10))
print(np.random.randint(5,10,9))
print(np.random.randint(5,10,(3,3)))

 uniform distribution
[[0.76841187 0.59957776 0.52473406]
 [0.19497108 0.58491702 0.43580996]]
[[0.906262   0.55589599 0.73821926]
 [0.1232696  0.43896882 0.08945832]]

 normal distribution
[[-0.22084044  0.06659412  0.22381101]
 [-0.21810647  1.08242378  0.11712263]]
[[-1.53596129  1.5431361   0.41227959]
 [-0.22195598 -0.66118954 -0.72049439]]

 random integer
13
[ 8 11 22 27 14  3  2 26 25 22]
[6 6 6 7 8 7 9 5 7]
[[7 9 9]
 [7 6 8]
 [9 7 5]]


In [39]:
x = np.arange(9)
print(x),x[3:6]

[0 1 2 3 4 5 6 7 8]


(None, array([3, 4, 5]))

In [49]:
x = np.arange(125)
x.resize((5,5))
print(x)
print('\n')
print(x[2,3])
print(x[2,(1,4)])
print(x[2, 1:4])
print('\n')
print(x[x>13])

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


13
[11 14]
[11 12 13]


[14 15 16 17 18 19 20 21 22 23 24]


In [54]:
print(x[x>13])
print('\n')
print('broadcast')
#print( x[x>13]=0 )

[14 15 16 17 18 19 20 21 22 23 24]


broadcast


In [58]:
x[x>13]=0
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13,  0],
       [ 0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0]])

In [82]:
# NUMPY ASSIGNMENT

# Use your understanding of the concepts to arrive at your solution and be as flexible and creative as possible.



# 1. Import NumPy Library as np
import numpy as np

# 2. Create an array of integers starting from 15 to 40 and store it in a variable called array1
array1 = np.arange(15,41)
print(array1)

# 2.1. Create a second array of integers starting from 10 until 25 and store it in a variable called array2
array2 = np.arange(10,26)
print(array2)

# 2.2. What is the difference between the two arrays?
#print('difference : ', array1-array2)
print( np.diff(array1) )
print( np.diff(array2) )

# 3. Create an array of all even integers from 2 to 20 and name it even_aaray1
even_aaray1 = np.arange(2,21,2)
print(even_aaray1)

# 3.1. Create an array of all even integers from 34 to 42 and name it even_array2
even_array2 = np.arange(34,43,2)
print(even_array2)

# 3.2. Create a matrix of the two arrays using the stack function
#even_aaray1.resize((2,5))
#np.stack((even_aaray1,even_array2))


# 4. Create a 6×6 matrix with values ranging from 0 to 36 and retrieve the intersection of the 3rd row and 2nd column
n = np.arange(0,36)
print(n)

m = n.reshape((6,6))
print(m)

print(m[2,1])

# 4.1. Create a 5×2 matrix from a standard normal distribution generated with python.
s = np.random.standard_normal(10)
print(s)
sm = s.reshape((5,2))
print(sm)

# 4.2. Retrieve the value intersecting the last row and the last column of your matrix
print(sm[-1,-1])

# 5. Using your matrix created at 4.1, calculate the following:

# a. minimum of the matrix
print(np.min(sm))

# b. maximum of the matrix
print(np.max(sm))

# c. standard deviation of the matrix
print(np.std(sm))

# d. variance of the matrix
print(np.var(sm))

# e. mean of the matrix
print(np.mean(sm))

[15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38
 39 40]
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25]
[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
[ 2  4  6  8 10 12 14 16 18 20]
[34 36 38 40 42]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]
13
[-0.37553651 -0.1810359  -2.28344466 -1.24978105 -0.25685139  0.19291065
  1.37284089  0.0285049   0.48265181  0.19582085]
[[-0.37553651 -0.1810359 ]
 [-2.28344466 -1.24978105]
 [-0.25685139  0.19291065]
 [ 1.37284089  0.0285049 ]
 [ 0.48265181  0.19582085]]
0.19582084978001174
-2.2834446583095813
1.3728408926178488
0.9370031829621335
0.8779749648811693
-0.207392040112363


In [86]:
! pip install pandas

     ---------------------------------------- 10.7/10.7 MB 7.1 MB/s eta 0:00:00
     -------------------------------------- 502.3/502.3 KB 6.3 MB/s eta 0:00:00
     -------------------------------------- 341.8/341.8 KB 5.3 MB/s eta 0:00:00


You should consider upgrading via the 'C:\Users\anand\Downloads\PYF2\0 Git repos (X don't delete)\repos\Scripts\python.exe -m pip install --upgrade pip' command.


In [91]:

Dict = {'a': 'Geeks', 'b': 'For', 'c': 'Geeks'}
print(Dict)

{'a': 'Geeks', 'b': 'For', 'c': 'Geeks'}


In [92]:
Dict.keys()

dict_keys(['a', 'b', 'c'])

In [93]:
import pandas as pd
df1 = pd.DataFrame(Dict,index = Dict.keys())
df1

a    b      c
a  Geeks  For  Geeks
b  Geeks  For  Geeks
c  Geeks  For  Geeks

In [97]:
Dict

{'a': 'Geeks', 'b': 'For', 'c': 'Geeks'}

In [95]:
df2 = pd.DataFrame.from_dict(Dict, orient='columns' )
df3 = pd.DataFrame.from_dict(Dict, orient= 'index' )
df4 = pd.DataFrame.from_dict(Dict, orient= 'tight' )
print(df2)

TypeError: from_dict() got an unexpected keyword argument 'index'

In [104]:
pd.DataFrame.from_dict(Dict, orient= 'index' , columns = ['now'] ).reset_index()

index    now
0     a  Geeks
1     b    For
2     c  Geeks